GET http://127.0.0.1:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmlrcmFtIiwiaWF0IjoxNTg4MTQwNzM2fQ.f-vQJ2Pn4G1pEToOc6WYrg_rY4jYSt-FSum9fPESPpA

###

POST http://127.0.0.1:3000/login
Content-Type: application/json

{
    "username" : "Vikram"
}

###

POST http://127.0.0.1:3000/token
Content-Type: application/json

{
    "refreshtoken" :  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmlrcmFtIiwiaWF0IjoxNTg4MTQzMTM2fQ.4TYXwMRQhV4m6cQ5yUHZm5J3-XGB34oEiY7odgGu0Jg"
}